#include <algorithm>
#include <array>
#include <chrono>
#include <cstdint>
#include <filesystem>
#include <fstream>
#include <iostream>
#include <map>
#include <numeric>
#include <stdexcept>
#include <unordered_map>
#include <vector>
using V=std::array<int,22>; using M=std::array<V,22>;
using Clock=std::chrono::steady_clock;
void need(bool ok,const char*s){if(!ok)throw std::runtime_error(s);}
struct VH{size_t operator()(V const&x)const{uint64_t h=1469598103934665603ULL;for(int z:x){h^=uint32_t(z);h*=1099511628211ULL;}return h;}};
struct MH{size_t operator()(M const&x)const{uint64_t h=1469598103934665603ULL;for(auto&r:x)for(int z:r){h^=uint32_t(z);h*=1099511628211ULL;}return h;}};
int checked(long long z){need(z>-100000000&&z<100000000,"integer intermediate exceeds certified range");return int(z);}
M mul(M const&a,M const&b){M c{};for(int i=0;i<22;++i)for(int j=0;j<22;++j){long long z=0;for(int k=0;k<22;++k)z+=(long long)a[i][k]*b[k][j];c[i][j]=checked(z);}return c;}
V mul(M const&a,V const&b){V c{};for(int i=0;i<22;++i){long long z=0;for(int j=0;j<22;++j)z+=(long long)a[i][j]*b[j];c[i]=checked(z);}return c;}
M transpose(M const&a){M c{};for(int i=0;i<22;++i)for(int j=0;j<22;++j)c[i][j]=a[j][i];return c;}
V canon(V x){for(int z:x)if(z){if(z<0)for(int&v:x)v=-v;break;}return x;}
int norm(V const&v,M const&G){auto w=mul(G,v);long long z=0;for(int i=0;i<22;++i)z+=(long long)v[i]*w[i];need(z>0&&z%2==0,"positive even norm");return checked(z/2);}
void vec(std::ostream&o,V const&v){for(int x:v)o<<' '<<x;}
void matrix(std::ostream&o,M const&m){for(auto&r:m){for(int j=0;j<22;++j){if(j)o<<' ';o<<r[j];}o<<'\n';}}
int main(int argc,char**argv){try{
 need(argc>=4&&argc<=6,"usage minima_orbits M_integer_data.txt shell.txt output_directory [maximum_trace_bound=24] [--orbits-only]");int max_trace=argc>4?std::stoi(argv[4]):24;need(max_trace>0,"positive trace cutoff");bool export_group=argc<=5||std::string(argv[5])!="--orbits-only";auto start=Clock::now();std::filesystem::path out(argv[3]);std::filesystem::create_directories(out);
 std::ifstream f(argv[1]);int n,ng;f>>n;need(n==22,"ambient dimension");M G{},W{};for(auto m:{&G,&W})for(auto&r:*m)for(int&z:r){f>>z;checked(z);}f>>ng;need(ng>0&&ng<=10,"generator count");std::vector<M> gen(ng);for(auto&m:gen)for(auto&r:m)for(int&z:r){f>>z;checked(z);}need(bool(f),"complete ambient input");need(G==transpose(G),"symmetric ambient Gram");M id{};for(int i=0;i<22;++i)id[i][i]=1;auto WW=mul(W,W),GW=mul(G,W),WtG=mul(transpose(W),G);for(int i=0;i<22;++i)for(int j=0;j<22;++j){need(WW[i][j]-W[i][j]+6*(i==j)==0,"omega polynomial");need(GW[i][j]+WtG[i][j]==G[i][j],"omega adjoint");}
 for(auto&m:gen){need(mul(transpose(m),mul(G,m))==G,"generator G preservation");need(mul(m,W)==mul(W,m),"generator O linearity");}
 // The complete finite semigroup generated by isometries and identity is a group.
 // Preserve the discovery tree and every generator edge, so every exported
 // matrix is a certified product and closure can be audited independently.
 std::vector<M> group;group.reserve(20000);group.push_back(id);std::unordered_map<M,int,MH> gids;gids.reserve(40000);gids.emplace(id,0);std::ofstream tree(out/"group_discovery.tsv"),edges(out/"group_edges.tsv");tree<<"id\tparent\tgenerator\n0\t-1\t-1\n";edges<<"from\tgenerator\tto\n";
 if(export_group)for(size_t i=0;i<group.size();++i)for(int j=0;j<ng;++j){M m=mul(gen[j],group[i]);auto[it,newone]=gids.emplace(m,group.size());if(newone){need(group.size()<100000,"unexpected group growth");group.push_back(m);tree<<it->second<<'\t'<<i<<'\t'<<j<<'\n';}edges<<i<<'\t'<<j<<'\t'<<it->second<<'\n';}
 auto group_done=Clock::now();if(export_group){std::ofstream gm(out/"group_matrices.txt"),gg(out/"group_matrices.gp");gm<<22<<' '<<group.size()<<'\n';gg<<"MINIMA_GROUP=[";for(size_t k=0;k<group.size();++k){auto&m=group[k];matrix(gm,m);if(k)gg<<','<<char(92)<<'\n';gg<<'[';for(int i=0;i<22;++i){if(i)gg<<';';for(int j=0;j<22;++j){if(j)gg<<',';gg<<m[i][j];}}gg<<']';}gg<<"];\n";}
 std::ifstream sf(argv[2]);int nv;sf>>nv>>n;need(n==22&&nv>0,"shell header");std::vector<V> vs(nv);std::vector<int> q(nv),parent(nv);std::unordered_map<V,int,VH> point;point.reserve(nv*2);for(int i=0;i<nv;++i){for(int&z:vs[i]){sf>>z;checked(z);}vs[i]=canon(vs[i]);q[i]=norm(vs[i],G);need(2*q[i]<=max_trace,"shell cutoff");need(point.emplace(vs[i],i).second,"unique signed vector pair");parent[i]=i;}need(bool(sf),"complete shell input");auto find=[&](int a){while(a!=parent[a])a=parent[a]=parent[parent[a]];return a;};
 for(int i=0;i<nv;++i)for(auto&m:gen){V u=canon(mul(m,vs[i]));auto it=point.find(u);need(it!=point.end(),"shell closed under generators");int a=find(i),b=find(it->second);if(a!=b)parent[b]=a;}
 std::map<int,int> representative;for(int i=0;i<nv;++i){int a=find(i);auto it=representative.find(a);if(it==representative.end()||vs[i]<vs[it->second])representative[a]=i;}
 std::vector<int> reps;for(auto[a,b]:representative)reps.push_back(b);std::sort(reps.begin(),reps.end(),[&](int a,int b){return q[a]!=q[b]?q[a]<q[b]:vs[a]<vs[b];});std::map<int,int> oid;for(int r=0;r<(int)reps.size();++r)oid[find(reps[r])]=r;std::vector<int> orbit(nv),sizes(reps.size());for(int i=0;i<nv;++i){orbit[i]=oid.at(find(i));++sizes[orbit[i]];}
 auto orbits_done=Clock::now();
 std::ofstream po(out/"point_orbit_lookup.txt"),rp(out/"orbit_representatives.txt"),st(out/"stabilizers.jsonl"),sm(out/"stabilizer_matrices.txt"),rg(out/"orbit_representatives.gp");rg<<"MINIMA_ORBIT_REPS=[";po<<nv<<' '<<22<<'\n';std::vector<int> order(nv);std::iota(order.begin(),order.end(),0);std::sort(order.begin(),order.end(),[&](int a,int b){return q[a]!=q[b]?q[a]<q[b]:vs[a]<vs[b];});for(int i:order){po<<q[i]<<' '<<orbit[i];vec(po,vs[i]);po<<'\n';}rp<<reps.size()<<' '<<22<<'\n';long stabilizer_count=0;std::map<int,int> shell_sizes,shell_orbits;for(int i=0;i<nv;++i)++shell_sizes[q[i]];
 for(int r=0;r<(int)reps.size();++r){int i=reps[r];++shell_orbits[q[i]];rp<<r<<' '<<q[i]<<' '<<sizes[r];vec(rp,vs[i]);rp<<'\n';if(r)rg<<',';rg<<'['<<r<<','<<q[i]<<','<<sizes[r]<<",[";for(int j=0;j<22;++j){if(j)rg<<',';rg<<vs[i][j];}rg<<"]]";if(!export_group)continue;std::vector<int> stab;std::unordered_map<V,int,VH> image_set;image_set.reserve(sizes[r]*2);
  for(int k=0;k<(int)group.size();++k){V image=canon(mul(group[k],vs[i]));auto pt=point.find(image);need(pt!=point.end()&&orbit[pt->second]==r,"full group image has correct orbit");image_set.emplace(image,0);if(image==vs[i])stab.push_back(k);}
  need(image_set.size()==(size_t)sizes[r],"full group orbit equals generator orbit");need((size_t)sizes[r]*stab.size()==group.size(),"orbit stabilizer identity");st<<"{\"orbit_id\":"<<r<<",\"q\":"<<q[i]<<",\"pair_orbit_size\":"<<sizes[r]<<",\"stabilizer_group_ids\":[";for(size_t k=0;k<stab.size();++k){if(k)st<<',';st<<stab[k];sm<<r<<' '<<stab[k]<<'\n';matrix(sm,group[stab[k]]);}st<<"]}\n";stabilizer_count+=stab.size();}
 rg<<"];\n";rg.close();po.close();rp.close();st.close();sm.close();auto end=Clock::now();std::cout<<"{\"status\":\"verified\",\"dimension\":22,\"group_order\":"<<(export_group?group.size():0)<<",\"generator_count\":"<<ng<<",\"maximum_trace_bound\":"<<max_trace<<",\"export_group\":"<<(export_group?"true":"false")<<",\"pair_count\":"<<nv<<",\"orbit_count\":"<<reps.size()<<",\"stabilizer_count\":"<<stabilizer_count<<",\"group_seconds\":"<<std::chrono::duration<double>(group_done-start).count()<<",\"shell_orbits_seconds\":"<<std::chrono::duration<double>(orbits_done-group_done).count()<<",\"stabilizers_export_seconds\":"<<std::chrono::duration<double>(end-orbits_done).count()<<",\"total_seconds\":"<<std::chrono::duration<double>(end-start).count()<<",\"shells\":[";bool sep=false;for(auto[q,s]:shell_sizes){if(sep)std::cout<<',';sep=true;std::cout<<"{\"q\":"<<q<<",\"pairs\":"<<s<<",\"orbits\":"<<shell_orbits[q]<<'}';}std::cout<<"]}\n";return 0;
 }catch(std::exception const&e){std::cerr<<"ERROR "<<e.what()<<'\n';return 1;}}
