default(nbthreads,1);
default(parisizemax,4000000000);
default(realprecision,100);
need(b,s)={if(!b,error(s))};
coordinates(v,basis)={my(B=matrix(poldegree(component(v,1)),#basis,i,j,polcoef(lift(basis[j]),i-1)));matinverseimage(B,vector(matsize(B)[1],i,polcoef(lift(v),i-1))~)};
certify(b,name)={need(bnfcertify(b)==1,Str(name," unconditional class group"));print(name," class_number=",b.no," cyclic=",b.cyc," signature_rank=",matrank(Mod(concat(matrix(b.r1,1,i,j,1),matrix(b.r1,#b.fu,i,j,(1-bnfsignunit(b)[i,j])/2)),2)));write(Str(OUT,"/number_fields.gp"),Str(name,"=",b,";"));};
main()={
 my(start=getwalltime(),F=bnfinit(x^2-x+6,1),K=bnfinit(polcyclo(23),1),eta,t,s,p,J,Jb,I,bb,beta,u,C,cc,realbeta,v,ep,cp,plus,KE,pr,er,z,w,delta,barx,N,um,sg,imgs,coords,nu,M,signrank,normrank);
 certify(F,"F");need(F.cyc==[3],"Cl F");
 eta=Mod(x,K.pol);t=eta+eta^-1;plus=bnfinit(minpoly(t),1);certify(plus,"K23plus");need(plus.no==1 && bnrclassno(plus,[1,vector(11,i,1)])==1,"narrow class number");
 certify(K,"K23");need(K.cyc==[3],"Cl K23");
 s=sum(i=1,22,kronecker(i,23)*eta^i);w=(1+s)/2;
 p=idealhnf(K,2,w);J=idealhnf(K,47,eta-21);Jb=idealhnf(K,47,eta^-1-21);
 need(bnfisprincipal(K,J,0)==bnfisprincipal(K,p,0),"J and p class");
 I=idealdiv(K,idealdiv(K,J,Jb),idealhnf(K,2,1-w));bb=bnfisprincipal(K,I,1);need(bb[1]==0,"beta ideal principal");beta=nfbasistoalg(K,bb[2]);
 u=2*beta*subst(lift(beta),x,eta^-1);
 C=matrix(22,11,i,j,polcoef(lift(t^(j-1)),i-1));cc=matinverseimage(C,vector(22,i,polcoef(lift(u),i-1))~);need(#cc==11,"real unit coordinates");
 realbeta=Mod(sum(i=1,11,cc[i]*x^(i-1)),plus.pol);ep=bnfisunit(plus,realbeta);need(#ep==11 && ep[11]%2==0 && sum(i=1,10,ep[i]%2)==0,"positive unit is square");
 v=prod(i=1,10,plus.fu[i]^(ep[i]/2));beta/=subst(lift(v),x,t);need(2*beta*subst(lift(beta),x,eta^-1)==1,"normalized beta norm");need(idealhnf(K,beta)==I,"normalized beta ideal");
 write(Str(OUT,"/explicit_beta.gp"),Str("KPOL=",K.pol,";BETA=",beta,";IDEAL_J=",J,";IDEAL_P=",p,";"));
 print("BETA_VERIFIED exact ideal and norm identities");
 cp=polcompositum(x^2-x+6,polcyclo(5),1)[1];KE=bnfinit(cp[1],1);w=cp[2];z=cp[3];s=2*w-1;u=s*(z-z^-1);pr=minpoly(u);er=bnfinit(pr,1);
 certify(KE,"Efield");certify(er,"Eplus");
 delta=(11*s*(z-z^-1)*(z+z^-1)-2*s*(z-z^-1)-115*(z+z^-1)+115)/2;
 barx=z^-1-(1-w);
 need(subst(lift(Mod(x,cp[1])),x,barx)==barx && subst(lift(w),x,barx)==1-w && subst(lift(z),x,barx)==z^-1,"conjugation E");
 need(idealhnf(KE,delta)==idealhnf(KE,KE.diff),"absolute different E");
 C=matrix(8,4,i,j,polcoef(lift(u^(j-1)),i-1));cc=matinverseimage(C,vector(8,i,polcoef(lift(delta),i-1))~);need(#cc==4,"delta real coordinates");
 need(vecmin(nfeltembed(er,Mod(sum(i=1,4,cc[i]*x^(i-1)),pr)))>0,"delta total positivity");
 sg=concat(matrix(4,1,i,j,1),matrix(4,3,i,j,(1-bnfsignunit(er)[i,j])/2));signrank=matrank(Mod(sg,2));imgs=matrix(4,3);
 for(j=1,3,nu=KE.fu[j]*subst(lift(KE.fu[j]),x,barx);cc=matinverseimage(C,vector(8,i,polcoef(lift(nu),i-1))~);ep=bnfisunit(er,Mod(sum(i=1,4,cc[i]*x^(i-1)),pr));need(#ep==4,"unit norm coordinates");imgs[,j]=concat([ep[4]],Vec(ep[1..3]))~);
 need(Mod(sg*imgs,2)==0,"unit norm positive");normrank=matrank(Mod(imgs,2));need(normrank==4-signrank,"unit norm surjectivity modulo squares");
 write(Str(OUT,"/E_units.gp"),Str("E_COMPOSITUM=",cp,";REAL_GENERATOR=",u,";REAL_POL=",pr,";SIGN_MATRIX=",sg,";NORM_EXPONENTS=",imgs,";"));
 print("E_UNITS_VERIFIED signature_rank=",signrank," norm_rank_mod_squares=",normrank);
 print("FIELD_ARITHMETIC_COMPLETE milliseconds=",getwalltime()-start);
};
main();
quit;
